check_rules <<'---';
WEIGHT_SPACE : VERTICES, LINEALITY_SPACE, MAXIMAL_POLYTOPES, CODIMENSION_ONE_POLYTOPES, MAXIMAL_AT_CODIM_ONE, LATTICE_NORMALS, PROJECTIVE_DIM, PROJECTIVE_AMBIENT_DIM 
*
WEIGHT_SYSTEM : WEIGHT_SPACE
*
WEIGHT_CONE : WEIGHT_SYSTEM, N_MAXIMAL_POLYTOPES
*
IS_IRREDUCIBLE : WEIGHT_SPACE, WEIGHTS
*
---
