<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1 class="extension">extension: bundled:cdd</h1>
  <p>  cddlib<br xmlns="http://www.w3.org/1999/xhtml"/>  Implementation of the double description method of Motzkin et al.<br xmlns="http://www.w3.org/1999/xhtml"/>  Copyright by Komei Fukuda.<br xmlns="http://www.w3.org/1999/xhtml"/>  http://www.ifor.math.ethz.ch/~fukuda/cdd_home/cdd.html<br xmlns="http://www.w3.org/1999/xhtml"/></p>
</div>
