<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1 class="extension">extension: bundled:javaview</h1>
  <p>  JavaView is a 3D geometry viewer and a mathematical visualization software.<br xmlns="http://www.w3.org/1999/xhtml"/>  Copyright by Konrad Polthier and JavaView Project Team.<br xmlns="http://www.w3.org/1999/xhtml"/>  http://www.javaview.de/</p>
</div>
