<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1 class="extension">extension: bundled:libnormaliz</h1>
  <p>  Normaliz is a tool for computations in affine monoids, vector configurations, lattice polytopes, and rational cones.<br xmlns="http://www.w3.org/1999/xhtml"/>  Copyright by Winfried Bruns, Bogdan Ichim, Christof Soeger.<br xmlns="http://www.w3.org/1999/xhtml"/>  http://www.math.uos.de/normaliz/<br xmlns="http://www.w3.org/1999/xhtml"/></p>
</div>
