<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1 class="extension">extension: bundled:ppl</h1>
  <p>  The Parma Polyhedra Library (PPL): A C++ library for convex polyhedra<br xmlns="http://www.w3.org/1999/xhtml"/>  and other numerical abstractions.<br xmlns="http://www.w3.org/1999/xhtml"/>  http://www.cs.unipr.it/ppl/<br xmlns="http://www.w3.org/1999/xhtml"/></p>
</div>
