<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1 class="extension">extension: bundled:lrs</h1>
  <p>  Implementation of the reverse search algorithm of Avis and Fukuda.<br xmlns="http://www.w3.org/1999/xhtml"/>  Copyright by David Avis.<br xmlns="http://www.w3.org/1999/xhtml"/>  http://cgm.cs.mcgill.ca/~avis/lrs.html<br xmlns="http://www.w3.org/1999/xhtml"/></p>
</div>
