<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content">
  <h1>polymake: index</h1>
  <p>This table contains all entities available in polymake in alphabetical order.</p>
  <p>For everything listed, the <b>name</b>, the <b>type</b> (i.e., one of object, property, function, property-type, application, option, common-option-list or permutation), the corresponding <b>application</b> and, for properties and user-methods the <b>object</b> or <b>property-type</b> which they belong to are given.</p>
  <br/>
  <table border="1">
    <tr>
      <th align="left">Name</th>
      <th align="left">Type</th>
      <th align="left">Object or Property-Type</th>
      <th align="left">Application</th>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#add_morphisms">add_morphisms</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__affine_chart">affine_chart</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#affine_linear_space">affine_linear_space</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__affine_representation">affine_representation</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#affine_transform__Cycle_Addition__Matrix_Rational__Vector_Rational">affine_transform</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#affine_transform__Cycle_Addition__Morphism_Addition">affine_transform</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__after">after</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__all_families">all_families</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__all_isolated">all_isolated</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__AMBIENT_DIM">AMBIENT_DIM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_family_fixed_edge">array_family_fixed_edge</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_family_fixed_vertex">array_family_fixed_vertex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_family_moving_edge">array_family_moving_edge</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_family_moving_vertex">array_family_moving_vertex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_isolated_edge">array_isolated_edge</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__array_isolated_no_edge">array_isolated_no_edge</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__BALANCED_FACES">BALANCED_FACES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__BB_VISUAL">BB_VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__BB_VISUAL">BB_VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__BB_VISUAL">BB_VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__before">before</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">BoundingBox</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">BoundingDistance</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">BoundingMode</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__bounding_box">bounding_box</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cartesian_product">cartesian_product</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#ch2d_3phases">ch2d_3phases</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_decorations">Chart</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_decorations">Visual::Cycle::decorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Chart</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#check_cycle_equality">check_cycle_equality</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#check_minimality">check_minimality</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#coarsen">coarsen</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#coarse_types">coarse_types</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__CODIMENSION_ONE_POLYTOPES">CODIMENSION_ONE_POLYTOPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__CodimPerm">CodimPerm</a>
        </b>
      </td>
      <td>permutation</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__COEFFICIENTS">COEFFICIENTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__COEFFS">COEFFS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">ConeLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#contains_point">contains_point</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__CONVEX_HULL_2D_CYCLIC">CONVEX_HULL_2D_CYCLIC</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">CoordLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cornered_hull">cornered_hull</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cornered_hull_poly">cornered_hull_poly</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#count_mn_cones">count_mn_cones</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#count_mn_rays">count_mn_rays</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cross_variety">cross_variety</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__CUBIC">CUBIC</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cutting_functions">cutting_functions</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle">Cycle</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#cyclic">cyclic</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#decomposition_polytope">decomposition_polytope</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__DEGREE">DEGREE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#degree">degree</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__delocalize">delocalize</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__DENOMINATOR">DENOMINATOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#discard_non_vertices">discard_non_vertices</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#divisor">divisor</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#divisor_nr">divisor_nr</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__DOMAIN">DOMAIN</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__DOMAIN">DOMAIN</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__DOME">DOME</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dualize">dualize</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__Cycle_Addition__Bool">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__TropicalNumber_Addition__Bool">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__Vector_TropicalNumber_Addition___Bool">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__Matrix_TropicalNumber_Addition___Bool">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__Ring_TropicalNumber_Addition_">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#dual_addition_version__Polynomial_TropicalNumber_Addition___Bool">dual_addition_version</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#empty_cycle">empty_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__ENVELOPE">ENVELOPE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#evaluation_map__Int__Matrix_Rational__Int">evaluation_map</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#evaluation_map__Int__Int__Int__Int">evaluation_map</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#extract_pseudovertices">extract_pseudovertices</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__facet_normal">facet_normal</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__FACET_NORMALS_BY_PAIRS">FACET_NORMALS_BY_PAIRS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#fan_decomposition">fan_decomposition</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#forgetful_map">forgetful_map</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_FunctionDecorations">FunctionLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_FunctionDecorations">Visual::Cycle::FunctionDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#get_corners">get_corners</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#gfan_tropicalbruteforce">gfan_tropicalbruteforce</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#gfan_tropicalhypersurface">gfan_tropicalhypersurface</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#gfan_tropicalintersection">gfan_tropicalintersection</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#gfan_tropicalvariety_of_prime">gfan_tropicalvariety_of_prime</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__GRAPH">GRAPH</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__GRAPH_EDGE_LENGTHS">GRAPH_EDGE_LENGTHS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#halfspace_subdivision">halfspace_subdivision</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__HALF_SPACES">HALF_SPACES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hurwitz_cycle">hurwitz_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hurwitz_marked_cycle">hurwitz_marked_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hurwitz_pair">hurwitz_pair</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hurwitz_pair_local">hurwitz_pair_local</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hurwitz_subdivision">hurwitz_subdivision</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hyperplane">hyperplane</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hypersimplex">hypersimplex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface">Hypersurface</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#hypersurface_union">hypersurface_union</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__INPUT_COEFFS">INPUT_COEFFS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__INPUT_SETS">INPUT_SETS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__INPUT_STRING">INPUT_STRING</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#insert_leaves">insert_leaves</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#insert_rays">insert_rays</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#intersect">intersect</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#intersect_check_transversality">intersect_check_transversality</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#intersect_container">intersect_container</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#intersect_in_smooth_surface">intersect_in_smooth_surface</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__IS_BALANCED">IS_BALANCED</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#is_balanced">is_balanced</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#is_empty">is_empty</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__is_fan">is_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__IS_GLOBALLY_AFFINE_LINEAR">IS_GLOBALLY_AFFINE_LINEAR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__IS_GLOBALLY_DEFINED">IS_GLOBALLY_DEFINED</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__IS_IRREDUCIBLE">IS_IRREDUCIBLE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#is_smooth">is_smooth</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_BASES">LATTICE_BASES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_GENERATORS">LATTICE_GENERATORS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#lattice_index">lattice_index</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__lattice_normal">lattice_normal</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_NORMALS">LATTICE_NORMALS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_NORMAL_FCT_VECTOR">LATTICE_NORMAL_FCT_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_NORMAL_SUM">LATTICE_NORMAL_SUM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LATTICE_NORMAL_SUM_FCT_VECTOR">LATTICE_NORMAL_SUM_FCT_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_RationalCurve_decorations">LengthLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_RationalCurve_decorations">Visual::RationalCurve::decorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#lifted_pluecker">lifted_pluecker</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__LINEALITY_VALUES">LINEALITY_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__LINEALITY_VALUES">LINEALITY_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic">LinesInCubic</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#lines_in_cubic">lines_in_cubic</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_FAMILY_FIXED_EDGE">LIST_FAMILY_FIXED_EDGE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_FAMILY_FIXED_VERTEX">LIST_FAMILY_FIXED_VERTEX</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_FAMILY_MOVING_EDGE">LIST_FAMILY_MOVING_EDGE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_FAMILY_MOVING_VERTEX">LIST_FAMILY_MOVING_VERTEX</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_ISOLATED_EDGE">LIST_ISOLATED_EDGE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__LIST_ISOLATED_NO_EDGE">LIST_ISOLATED_NO_EDGE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#local_codim_one">local_codim_one</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#local_m0n">local_m0n</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#local_point">local_point</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#local_restrict">local_restrict</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__LOCAL_RESTRICTION">LOCAL_RESTRICTION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#local_vertex">local_vertex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#m0n">m0n</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__MATRIX">MATRIX</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#matroid_coordinates_from_curve">matroid_coordinates_from_curve</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#matroid_fan__matroid_Matroid">matroid_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#matroid_fan__Matrix_Rational">matroid_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#matroid_fan_from_flats">matroid_fan_from_flats</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#matroid_from_fan">matroid_from_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__MAXIMAL_AT_CODIM_ONE">MAXIMAL_AT_CODIM_ONE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__metric_vector">metric_vector</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#minimal_tropical_halfspaces">minimal_tropical_halfspaces</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#minkowski_sum">minkowski_sum</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__MONOMIALS">MONOMIALS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism">Morphism</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#morphism_from_affine">morphism_from_affine</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#nearest_point">nearest_point</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__NODES_BY_LEAVES">NODES_BY_LEAVES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__NODES_BY_SETS">NODES_BY_SETS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__NODE_DEGREES">NODE_DEGREES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#norm">norm</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__NUMERATOR">NUMERATOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__N_FAMILIES">N_FAMILIES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__N_ISOLATED">N_ISOLATED</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__N_LEAVES">N_LEAVES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__opt_attained">opt_attained</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#orthant_subdivision">orthant_subdivision</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PseudoVertexPerm__PERMUTATION">PERMUTATION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__CodimPerm__PERMUTATION">PERMUTATION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#piecewise_divisor">piecewise_divisor</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__POINTS">POINTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#points2hypersurface">points2hypersurface</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#point_collection">point_collection</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#point_functions">point_functions</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#poly2trop">poly2trop</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__POLYNOMIAL">POLYNOMIAL</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#LinesInCubic__POLYNOMIAL">POLYNOMIAL</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#LinesInCubic">LinesInCubic</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__POWER">POWER</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__privileged_subdivision">privileged_subdivision</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#projection_map__Int__Set_Int">projection_map</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#projection_map__Int__Int">projection_map</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__PROJECTIVE_AMBIENT_DIM">PROJECTIVE_AMBIENT_DIM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__PROJECTIVE_CODIMENSION">PROJECTIVE_CODIMENSION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__PROJECTIVE_DIM">PROJECTIVE_DIM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#projective_torus">projective_torus</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__PROJECTIVE_VERTICES">PROJECTIVE_VERTICES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PseudoVertexPerm">PseudoVertexPerm</a>
        </b>
      </td>
      <td>permutation</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PSEUDOVERTEX_COARSE_TYPES">PSEUDOVERTEX_COARSE_TYPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PSEUDOVERTEX_GRAPH">PSEUDOVERTEX_GRAPH</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PSEUDOVERTEX_LABELS">PSEUDOVERTEX_LABELS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PSEUDOVERTEX_TYPES">PSEUDOVERTEX_TYPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__PSEUDOVERTICES">PSEUDOVERTICES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#pseudovertices2poly">pseudovertices2poly</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#psi_class">psi_class</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#psi_product">psi_product</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#pullback">pullback</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#randomInteger">randomInteger</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve">RationalCurve</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction">RationalFunction</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_from_cone">rational_curve_from_cone</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_from_matroid_coordinates">rational_curve_from_matroid_coordinates</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_from_metric">rational_curve_from_metric</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_from_rays">rational_curve_from_rays</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_immersion">rational_curve_immersion</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_list_from_matroid_coordinates">rational_curve_list_from_matroid_coordinates</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_curve_list_from_metric">rational_curve_list_from_metric</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_fct_from_affine_denominator__Polynomial_TropicalNumber_Addition___Int">rational_fct_from_affine_denominator</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_fct_from_affine_denominator__String__Int">rational_fct_from_affine_denominator</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_fct_from_affine_numerator__Polynomial_TropicalNumber_Addition___Int">rational_fct_from_affine_numerator</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#rational_fct_from_affine_numerator__String__Int">rational_fct_from_affine_numerator</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#recession_fan">recession_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__REDUNDANT_MONOMIALS">REDUNDANT_MONOMIALS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Hypersurface__REGIONS">REGIONS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Hypersurface">Hypersurface</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__restrict">restrict</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__restrict">restrict</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__SEPARATED_CODIMENSION_ONE_POLYTOPES">SEPARATED_CODIMENSION_ONE_POLYTOPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__SEPARATED_CONVERSION_VECTOR">SEPARATED_CONVERSION_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__SEPARATED_MAXIMAL_POLYTOPES">SEPARATED_MAXIMAL_POLYTOPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__SEPARATED_VERTICES">SEPARATED_VERTICES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__SETS">SETS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#set_theoretic_intersection">set_theoretic_intersection</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#shift_cycle">shift_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#simplicial_diagonal_system">simplicial_diagonal_system</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#simplicial_piecewise_system">simplicial_piecewise_system</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#simplicial_with_diagonal">simplicial_with_diagonal</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#skeleton_complex">skeleton_complex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#space_of_stable_maps">space_of_stable_maps</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#sum_curves">sum_curves</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#tdehomog">tdehomog</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#tdet">tdet</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#testFourPointCondition">testFourPointCondition</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#thomog">thomog</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__TRANSLATE">TRANSLATE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#triangulate_cycle">triangulate_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#trop2poly">trop2poly</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#">tropical</a>
        </b>
      </td>
      <td>application</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#tropical_complex">tropical_complex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#tropical_intersection">tropical_intersection</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#tropical_matroid_polytope">tropical_matroid_polytope</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#types">types</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#uniform_linear_space">uniform_linear_space</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VERTEX_LABELS">VERTEX_LABELS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VERTEX_TYPES">VERTEX_TYPES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalFunction__VERTEX_VALUES">VERTEX_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#RationalFunction">RationalFunction</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Morphism__VERTEX_VALUES">VERTEX_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Morphism">Morphism</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VERTICES">VERTICES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VISUAL">VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__VISUAL">VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#RationalCurve__VISUAL">VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#RationalCurve">RationalCurve</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_decorations">Visual::Cycle::decorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_FunctionDecorations">Visual::Cycle::FunctionDecorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_RationalCurve_decorations">Visual::RationalCurve::decorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#visualize_in_surface">visualize_in_surface</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VISUAL_HYPERPLANE_ARRANGEMENT">VISUAL_HYPERPLANE_ARRANGEMENT</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VISUAL_PLANAR">VISUAL_PLANAR</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#TropicalPolytope__VISUAL_PSEUDOVERTEX_GRAPH">VISUAL_PSEUDOVERTEX_GRAPH</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="tropical.html#TropicalPolytope">TropicalPolytope</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">WeightLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="tropical.html#options__Visual_Cycle_BoundingDecorations">Visual::Cycle::BoundingDecorations</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__WEIGHTS">WEIGHTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__WEIGHT_CONE">WEIGHT_CONE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#weight_cone">weight_cone</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__WEIGHT_SPACE">WEIGHT_SPACE</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="tropical.html#Cycle__WEIGHT_SYSTEM">WEIGHT_SYSTEM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="tropical.html#Cycle">Cycle</a>
      </td>
      <td>
        <a href="tropical.html">tropical</a>
      </td>
    </tr>
  </table>
</div>
