<div xmlns="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.org/ns/docs#3" id="content"><h1>polymake:extensions</h1>
  
        This is the list of all extensions installed in your version of polymake.

	
  2.14
  <ul class="ext"><li><a href="bundled_nauty.html&#10;&#9;&#9;&#9;&#9;">bundled:nauty</a></li><li><a href="bundled_lrs.html&#10;&#9;&#9;&#9;&#9;">bundled:lrs</a></li><li><a href="bundled_local.html&#10;&#9;&#9;&#9;&#9;">bundled:local</a></li><li><a href="bundled_libnormaliz.html&#10;&#9;&#9;&#9;&#9;">bundled:libnormaliz</a></li><li><a href="bundled_java.html&#10;&#9;&#9;&#9;&#9;">bundled:java</a></li><li><a href="bundled_cdd.html&#10;&#9;&#9;&#9;&#9;">bundled:cdd</a></li><li><a href="bundled_jreality.html&#10;&#9;&#9;&#9;&#9;">bundled:jreality</a></li><li><a href="bundled_javaview.html&#10;&#9;&#9;&#9;&#9;">bundled:javaview</a></li><li><a href="bundled_group.html&#10;&#9;&#9;&#9;&#9;">bundled:group</a></li><li><a href="https___github_com_simonhampe_atint.html&#10;&#9;&#9;&#9;&#9;">https://github.com/simonhampe/atint</a></li></ul>
</div>
