<div xmlns:html="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.de/ns/docs#3" id="content">
  <h1>polymake: index</h1>
  <p>This table contains all entities available in polymake in alphabetical order.</p>
  <p>For everything listed, the <b>name</b>, the <b>type</b> (i.e., one of object, property, function, property-type, application, option, common-option-list or permutation), the corresponding <b>application</b> and, for properties and user-methods the <b>object</b> or <b>property-type</b> which they belong to are given.</p>
  <br/>
  <table border="1">
    <tr>
      <th align="left">Name</th>
      <th align="left">Type</th>
      <th align="left">Object or Property-Type</th>
      <th align="left">Application</th>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i30">adjacencyComplex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i78">affineTransform</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i32">al_bmatrix</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i34">al_circuits</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i33">al_dependency</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#">atint</a>
        </b>
      </td>
      <td>application</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i72">atint_testrun</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i94">BB_VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i52">bergman_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i42">bergman_fan_linear</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i46">bergman_fan_matroid</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i18">BoundingBox</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i18">Visual::WeightedComplex::BoundingDecorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i110">boundingBox</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i18">BoundingDistance</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i18">Visual::WeightedComplex::BoundingDecorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i18">BoundingMode</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i18">Visual::WeightedComplex::BoundingDecorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i95">characteristic</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i123">CMPLX_AMBIENT_DIM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i122">CMPLX_CODIM_1_FACES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i113">CMPLX_CODIMENSION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i114">CMPLX_CONVERSION_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i115">CMPLX_DIM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i124">CMPLX_MAXIMAL_CONES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i116">CMPLX_RAYS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i109">CMPLX_VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i128">CODIM_1_FACES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i130">CODIM_1_IN_MAXIMAL_CONES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i150">COEFFS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i25">complexify</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i76">computeMatrixBases</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i75">computeMatrixColoops</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i143">CONSTANT_COEFFICIENTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i19">CoordLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i19">Visual::WeightedComplex::decorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i35">count_mn_cones</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i38">count_mn_rays</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i67">curve_graph_from_metric</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i59">cycle_intersection</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i51">degree</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i129">DESCRIPTION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i66">diagonal_functions</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i119">DIRECTIONAL_RAYS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i19">DirScale</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i19">Visual::WeightedComplex::decorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i60">divisor</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i57">divisorByPLF</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i41">divisorByValue</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i55">divisor_list</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i63">divisor_list_nr</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i45">divisor_nr</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i159">DOMAIN</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i137">DOMAIN_DIMENSION</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i29">equivalenceComplex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i70">fan_decomposition</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i141">FUNCTION_MATRIX</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i79">function_mult</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i80">function_value</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i73">gcdext</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i152">GRAPH</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i151">GRAPH_EDGE_LENGTHS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i37">halfspace_complex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i111">homogenize</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i156">homogenize</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i148">INPUT_COEFFS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i120">INPUT_HOM_LINEALITY</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i117">INPUT_HOM_RAYS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i153">INPUT_SETS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i147">INPUT_STRING</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i139">INPUT_STRING</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i140">INPUT_VARS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i62">intersect_complete_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i133">IS_BALANCED</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i58">is_zerocycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i65">latticeBasis</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i68">latticeNormal</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i112">lattice_normal</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i39">latticeNormalByCone</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i125">LATTICE_NORMAL_FCT_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i131">LATTICE_NORMALS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i127">LATTICE_NORMAL_SUM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i126">LATTICE_NORMAL_SUM_FCT_VECTOR</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i17">LengthLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i17">Visual::RationalCurve::decorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i142">LINEAR_COEFFICIENTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i135">linearityDomains</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i61">linear_nspace</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i77">linearRepresentation</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i71">linear_space_by_basis</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i47">linear_space_by_matrix</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i160">LIN_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i74">lllHNF</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i145">matroid_vector</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i146">metric_vector</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i21">MinMaxFunction</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i54">moduliDimensionFromLength</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i149">N_LEAVES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i136">NORMAL_FAN</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i155">pow</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i100">pow</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i157">POWER</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i26">product_complex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i28">randomInteger</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i53">random_minmaxdivisor</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i22">RationalCurve</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i82">rational_curve_from_metric</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i49">rational_curve_from_moduli</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i43">rational_curve_list_from_metric</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i40">rational_curve_list_from_moduli</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i23">RationalFunction</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i158">RAY_VALUES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i23">RationalFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i50">recession_fan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i154">SETS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i27">skeleton_complex</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i31">spanning_complete</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i144">STANDARD_FORM</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i56">sum_curves</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i44">testFourPointCondition</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i36">tropical_cube</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i48">tropical_lnk</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i69">tropical_m0n</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i132">TROPICAL_WEIGHTS</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i121">USES_HOMOGENEOUS_C</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i138">USES_MIN</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i134">valueAt</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i21">MinMaxFunction</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i118">VERTICES</a>
        </b>
      </td>
      <td>property</td>
      <td>
        <a href="atint.html#i20">WeightedComplex</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i103">VISUAL</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a href="atint.html#i22">RationalCurve</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i17">Visual::RationalCurve::decorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i18">Visual::WeightedComplex::BoundingDecorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i19">Visual::WeightedComplex::decorations</a>
        </b>
      </td>
      <td>common-option-list</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i20">WeightedComplex</a>
        </b>
      </td>
      <td>object</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i19">WeightLabels</a>
        </b>
      </td>
      <td>option</td>
      <td>
        <a href="atint.html#i19">Visual::WeightedComplex::decorations</a>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i81">wfan</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
    <tr>
      <td>
        <b>
          <a href="atint.html#i64">zero_cycle</a>
        </b>
      </td>
      <td>function</td>
      <td>
        <a/>
      </td>
      <td>
        <a href="atint.html">atint</a>
      </td>
    </tr>
  </table>
</div>
