<div xmlns="http://www.w3.org/1999/xhtml" xmlns:pm="http://www.polymake.de/ns/docs#3" id="content"><h1>Welcome to the documentation of <span class="pm">polymake</span></h1>
  
        This documentation constitutes a reference of all functions available in polymake  as of release 2.11.1 with the following individual extensions:<ul class="ext"><li>https://bitbucket.org/hampe/atint</li></ul><div class="level2"><h2><a name="apps">applications</a></h2><ul><li><a href="atint.html">atint</a></li></ul><h2><a href="core.html">core functionality</a></h2><a href="core.html">Core functionality</a> of polymake available in all applications.

          <h2><a href="doc_index.html">index</a></h2>
          The <a href="doc_index.html">index</a> contains an alphabetical list of all entities 
          (i.e., objects, properties, functions, types and applications) available in your version of polymake.

          </div></div>
