#include "polymake/client.h"

#ifndef ATINT_SPECIAL_VARIETIES_H
#define ATINT_SPECIAL_VARIETIES_H

/**
 * @brief Creates the linear tropical space L^n_k. This tropical fan is defined in the following way: 
 * As rays we take -e_i,i=1,...,n, where e_i is the i-th standard basis vector of R^n and 
 * e_0 = e_1 + ... + e_n. As maximal cones we take the cones generated by rays {e_i, i in S}, where
 * S runs over all k-element subsets of {0,..,n}.
 * @param n The ambient dimension of the fan.
 * @param k The dimension of the fan (should be smaller equal n, otherwise an error is thrown).
 * If k is zero, this creates the fan consisiting of the origin in R^n
 * @return A PolyhedralFan object representing L^n_k
 */
perl::Object tropical_lnk(const int &n, const int &k);

#endif